disabled = false
languageCode = "de"
languageName = "Deutsch"
weight = 2
title = "de-rse.org"

[params]
displayName = "DE"
isoCode = "de"
logo = "img/Logo.png"
rtl = false
dateFormat = "2 January 2006"
