[[main]]
name = "Aims"
pageRef = "aims"
weight = 10


[[main]]
name = "Positions"
pageRef = "positions"
weight = 20

[[main]]
name = "Working Groups"
pageRef = "working_groups"
weight = 30

[[main]]
name = "Join"
pageRef = "join"
weight = 40

[[main]]
name = "Events"
pageRef = "events"
weight = 50

[[main]]
name = "Map"
pageRef = "map"
weight = 60

[[main]]
name = "Blog"
pageRef = "blog"
weight = 70


[[main]]
name = "Association"
pageRef = "assoc"
weight = 80


[[main]]
name = "Code of Conduct"
pageRef = "coc"
weight = 90


[[main]]
name = "Matrix Chat"
pageRef = "matrix"
weight = 100

[[main]]
pre = "github"
url = "https://github.com/DE-RSE/de-rse.github.io"
weight = 110

[[footer]]
none = "none"
